### ISSUE TITLE
Clients disassociated every 10 seconds in SoftAP mode

### ISSUE THREAD

**Issue by projectgus** [SuperHouse/esp-open-rtos#140]
Copied in from mailing list post: https://groups.google.com/d/msg/esp-open-rtos/4BlYYrYRfH8/D72Jo-yyBgAJ

> 10 seconds after a client connects to the ESP in SoftAP mode, the AP disassociates it for inactivity (regardless of whether it was active or not). Some of my devices were transparently re-associating without me noticing, but not all of mine were (and some, like my Android phone, actually seem to get stuck where the device thinks it's still associated even though it isn't.)
> 
> The short/quick answer is that you can work around this by replacing the SDK's internal hostap timeout function. It's hacky (and it means clients will never get booted for inactivity), but you can do it by adding this code to your program:
> 
> void sdk_hostap_handle_timer(void *cnx_node)
> {
> }
> 
> ... full explanation of what I think the behaviour around the bug is:
> 
> * In libnet80211/ieee80211_hostap.o when hostap_input() sees packets from a new station, it calls a static function which adds the station to the internal connection table - via cnx_node_alloc() - and sets up a timer to call hostap_handle_timer() every 10 seconds (repeating). The argument passed to hostap_handle_timer() is the cnx_node structure that was just allocated.
> 
> * hostap_input is also supposed to look up each incoming packet's sender(?) in the internal connection table (cnx_node_search()), and if it finds a matching entry it writes the current count of hardware timer FRC2 to offset 0x108 in the allocated 'cnx_node' structure. This is a "last seen" timestamp.
> 
> * Every ten seconds the hostap_handle_timer() function compares the current FRC2 timer count to the stored timestamp, and if they're too far apart (ie no wifi frame received recently) then it sends a disassociation frame to the idle client and removes it using cnx_node_leave().
> 
> * cnx_node_leave() itself checks some internal state and prints the "max connection!" message each time it removes an "idle" client. (Unclear if this is a bug itself, or a symptom of the bug.)
> 
> 
> ... the bug happens because the "last frame received" timestamp is never written to offset 0x108 in hostap_input, this value is always zero so even an active client is disconnected after 10 seconds.
> 
> I don't know what causes that buggy behaviour. The bug could be in hostap_input, or maybe the "cnx node" is never properly registered.

**Comment by ourairquality** [comment]
Took a look at this, and thanks for all the analysis above. Found that `hostap_input` does update slot 0x108 but the context passed to `hostap_handle_timer` does not match the context it is writing into.

Quick look suggests that the problem is that the callback create with xTimerCreate receives a handle, and not the expected argument. Is it practical to implement every callback in C to change their handlers, or do we need a trampoline callback for handle this compatibility issue for now?

This might also explain some of the crashes in the timer paths.

**Comment by chennakeshavaSoC** [comment]
Is there any update on this 10 seconds timeout and max connection!

**Comment by ourairquality** [comment]
@chennakeshavaSoC It is fixed by https://github.com/SuperHouse/esp-open-rtos/issues/22 It has not been merged yet, but close when it has been.

**Comment by chennakeshavaSoC** [comment]
Thanks for quick response, I mean 
Clients disassociated every 10 seconds in SoftAP mode #140

Is there any updates on #140

**Comment by chennakeshavaSoC** [comment]
Can you please share us the fix code, I would like to use this functionality its a critical update for us.

**Comment by ourairquality** [comment]
@chennakeshavaSoC Sorry, copy typo, see https://github.com/SuperHouse/esp-open-rtos/issues/221 for the patch.

**Comment by rooi-oog** [comment]
I can't realize was this fixed or not? Because this issue still applying to me. Clients still disassociating. But not prints "max connection". And not after 10 seconds but 20.

**Comment by phlemoine** [comment]
It's working for me with the recent fix that got merged in master branch.
See #221

**Comment by rooi-oog** [comment]
I cloned repo 2 days ago. I just watched - yes that patch is present. But not working for me.

**Comment by ourairquality** [comment]
@rooi-oog If no one can reproduce this then it might be up to you to try to narrow it down. In case it helps please consider https://github.com/SuperHouse/esp-open-rtos/pull/224 which added open implementations of some function in these code paths. For example this allows you to instrument `sdk_hostap_handle_timer` to see if it is disassociating due to a timeout, and `sdk_cnx_node_search` was a good spot to dump the state.

**Comment by rooi-oog** [comment]
I just tried the workaround (sdk_hostap_handle_timer) and it works for me.
